[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  
[build]
  publish = "out"
  command = "npm run export"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"